In [34]:
import numpy as np
from pyfigtree import figtree
from sklearn import preprocessing
from scipy.optimize import root
from scipy.integrate import odeint


In [5]:
def direct_evaluation(S,T,weights,delta):
    checkPot = []
    for target in T:
        # for each source, add to potential at current target
        diff = target-S
        norm = np.linalg.norm(diff, axis=1)
        up = (norm / delta)**2
        potential = np.exp(-up)*weights
        
        cum_potential = np.sum(potential)
        checkPot.append(cum_potential)
    return np.array(checkPot)

In [6]:
delta = 6.5 * (2 ** 0.5)


#Direct Evaluation Test with sphere data
X = np.loadtxt('data/sphere_x.txt')
Y = np.loadtxt('data/sphere_y.txt')
Z = np.loadtxt('data/sphere_z.txt')

X0 = np.dstack((X,Y,Z))[0]

X = np.loadtxt('data/alpha0_x.txt')
Y = np.loadtxt('data/alpha0_y.txt')
Z = np.loadtxt('data/alpha0_z.txt')

alpha0 = np.dstack((X,Y,Z))[0]
weights = alpha0

In [7]:
cp_x = figtree(X0,X0,alpha0[:,0], delta,epsilon=1e-16, eval="auto")
cp_y = figtree(X0,X0,alpha0[:,1], delta,epsilon=1e-16, eval="auto")
cp_z = figtree(X0,X0,alpha0[:,2], delta,epsilon=1e-16, eval="auto")
cp = np.dstack([cp_x,cp_y, cp_z])[0]
diff = np.linalg.norm(X0[0] - X0, axis = 1) 
elev = - ((diff/delta) ** 2)
exp = np.exp(elev)
expA = exp * alpha0[:,2]
sumExpA = np.sum(expA)
print "sumExpA", sumExpA
print "elev", elev
print "exp", exp
print "alpha0[:,2]", alpha0[:,2]
print "expA", expA
print "sum alpha0", np.sum(alpha0, axis = 0)
print "alpha0[0]", alpha0[0]

sumExpA 5.28165726727
elev [ -0.         -15.33727811  -7.66863905 ...,  -3.10724165  -3.52191393
  -3.10724142]
exp [  1.00000000e+00   2.18325645e-07   4.67253298e-04 ...,   4.47241504e-02
   2.95428381e-02   4.47241607e-02]
alpha0[:,2] [ 0.021531 -0.046085  0.074488 ...,  0.71515  -3.383855 -4.354775]
expA [  2.15310000e-02  -1.00615373e-08   3.48047637e-05 ...,   3.19844762e-02
  -9.99686805e-02  -1.94763657e-01]
sum alpha0 [-29.746298 -33.989227  87.78351 ]
alpha0[0] [-0.037241 -0.077075  0.021531]


# Form Evolution Equations
## Direct Functions

In [8]:
def direct_position(X,alpha,delta):
    X_x = direct_evaluation(X,X,alpha[:,0], delta)
    X_y = direct_evaluation(X,X,alpha[:,1], delta)
    X_z = direct_evaluation(X,X,alpha[:,2], delta) 
    return np.dstack([X_x,X_y, X_z])[0]

In [21]:
def direct_momentum(X,alpha,delta):
    ax = alpha[:,0]
    ay = alpha[:,1]
    az = alpha[:,2]
    
    first_weights = np.dstack([ax * X[:,0], ax * X[:,1], ax * X[:,2]])[0]
    second_weights = np.dstack([ay * X[:,0], ay * X[:,1], ay * X[:,2]])[0]
    third_weights = np.dstack([az * X[:,0], az * X[:,1], az * X[:,2]])[0]
    
    first_sum_x = direct_evaluation(X,X,first_weights[:,0],delta)
    first_sum_y = direct_evaluation(X,X,first_weights[:,1],delta)
    first_sum_z = direct_evaluation(X,X,first_weights[:,2],delta)
    
    
    second_sum_x = direct_evaluation(X,X,second_weights[:,0],delta)
    second_sum_y = direct_evaluation(X,X,second_weights[:,1],delta)
    second_sum_z = direct_evaluation(X,X,second_weights[:,2],delta)
    
    
    third_sum_x = direct_evaluation(X,X,third_weights[:,0],delta)
    third_sum_y = direct_evaluation(X,X,third_weights[:,1],delta)
    third_sum_z = direct_evaluation(X,X,third_weights[:,2],delta)
    
    fourth_sum = direct_evaluation(X,X,ax,delta)
    fifth_sum = direct_evaluation(X,X,ay,delta)
    sixth_sum = direct_evaluation(X,X,az,delta)
    
    second_term = ax * fourth_sum + ay * fifth_sum + az * sixth_sum
    
    second_term_x = X[:,0] * second_term
    second_term_y = X[:,1] * second_term
    second_term_z = X[:,2] * second_term
    
    
    mult = -2./(delta ** 2)
    result_x = mult*(ax* first_sum_x + ay * second_sum_x + az * third_sum_x - (second_term_x) )
    result_y = mult*(ax* first_sum_y + ay * second_sum_y + az * third_sum_y - (second_term_y) )
    result_z = mult*(ax* first_sum_z + ay * second_sum_z + az * third_sum_z - (second_term_z) )
    result = np.dstack([result_x,result_y,result_z])[0]
    
    return result

## Figtree Functions

In [22]:
def position(X,alpha,delta):
    X_x = figtree(X,X,alpha[:,0], delta,epsilon=1e-16, eval="auto")
    X_y = figtree(X,X,alpha[:,1], delta,epsilon=1e-16, eval="auto")
    X_z = figtree(X,X,alpha[:,2], delta,epsilon=1e-16, eval="auto") 
    return np.dstack([X_x,X_y, X_z])[0]

In [23]:
def momentum(X,alpha,delta):
    ax = alpha[:,0]
    ay = alpha[:,1]
    az = alpha[:,2]
    
    first_weights = np.dstack([ax * X[:,0], ax * X[:,1], ax * X[:,2]])[0]
    second_weights = np.dstack([ay * X[:,0], ay * X[:,1], ay * X[:,2]])[0]
    third_weights = np.dstack([az * X[:,0], az * X[:,1], az * X[:,2]])[0]
    
    first_sum_x = figtree(X,X,first_weights[:,0],delta, epsilon=1e-16, eval="auto")
    first_sum_y = figtree(X,X,first_weights[:,1],delta, epsilon=1e-16, eval="auto")
    first_sum_z = figtree(X,X,first_weights[:,2],delta, epsilon=1e-16, eval="auto")
    
    
    second_sum_x = figtree(X,X,second_weights[:,0],delta, epsilon=1e-16, eval="auto")
    second_sum_y = figtree(X,X,second_weights[:,1],delta, epsilon=1e-16, eval="auto")
    second_sum_z = figtree(X,X,second_weights[:,2],delta, epsilon=1e-16, eval="auto")
    
    third_sum_x = figtree(X,X,third_weights[:,0],delta, epsilon=1e-16, eval="auto")
    third_sum_y = figtree(X,X,third_weights[:,1],delta, epsilon=1e-16, eval="auto")
    third_sum_z = figtree(X,X,third_weights[:,2],delta, epsilon=1e-16, eval="auto")
    
    fourth_sum = figtree(X,X,ax,delta, epsilon=1e-16, eval="auto")
    fifth_sum = figtree(X,X,ay,delta, epsilon=1e-16, eval="auto")
    sixth_sum = figtree(X,X,az,delta, epsilon=1e-16, eval="auto")
    
    second_term = ax * fourth_sum + ay * fifth_sum + az * sixth_sum
    
    second_term_x = X[:,0] * second_term
    second_term_y = X[:,1] * second_term
    second_term_z = X[:,2] * second_term
 
    mult = -2./(delta ** 2)
    result_x = mult*(ax* first_sum_x + ay * second_sum_x + az * third_sum_x - (second_term_x) )
    result_y = mult*(ax* first_sum_y + ay * second_sum_y + az * third_sum_y - (second_term_y) )
    result_z = mult*(ax* first_sum_z + ay * second_sum_z + az * third_sum_z - (second_term_z) )
    result = np.dstack([result_x,result_y,result_z])[0]
    
    return result

## Testing

In [12]:
delta = 6.5 * (2**0.5)

In [13]:
postition1 = direct_position(X0,alpha0,delta)
print postition1[0]

[-0.2980191   0.58632288  5.28165727]


In [14]:
postition2 = position(X0,alpha0,delta)
print postition2[0]

[-0.2980191   0.58632288  5.28165727]


In [15]:
%time momentum1 = direct_momentum(X0,alpha0,delta)
print momentum1
print np.linalg.norm(np.sum(momentum1, axis = 0))

CPU times: user 17.3 s, sys: 8 ms, total: 17.3 s
Wall time: 17.3 s
[[ 0.17683318  0.17610195  0.13309635]
 [-0.02536119 -0.05581413 -0.04250429]
 [-0.00615601 -0.01077219 -0.00665654]
 ..., 
 [ 0.07599794  0.07124645  0.04316963]
 [ 0.28857537  0.28275298  0.23682925]
 [ 0.4853737   0.45138054  0.39271936]]
312.488079815


In [16]:
%time momentum2 = momentum(X0,alpha0,delta)
print momentum2
print np.linalg.norm(np.sum(momentum2, axis = 0))

CPU times: user 7.7 s, sys: 0 ns, total: 7.7 s
Wall time: 7.69 s
[[ 0.17683318  0.17610195  0.13309635]
 [-0.02536119 -0.05581413 -0.04250429]
 [-0.00615601 -0.01077219 -0.00665654]
 ..., 
 [ 0.07599794  0.07124645  0.04316963]
 [ 0.28857537  0.28275298  0.23682925]
 [ 0.4853737   0.45138054  0.39271936]]
312.488079815


In [17]:
error_pos = np.sum(np.abs(postition1-postition2))
error_pos

6.1523361708989976e-11

In [18]:
error_mom = np.sum(np.abs(momentum1-momentum2))
error_mom

3.4264810024162325e-12

In [ ]:
def f(vector, delta):
    positions, momentums = np.split(vector,2)
    positions = np.reshape(positions,(3,len(positions)/3)).T
    momentums = np.reshape(momentums,(3,len(momentums)/3)).T
    new_positions = position(positions, momentums,delta)
    new_momentums = momentum(positions, momentums,delta)
    n,m = new_positions.shape
    new_positions = np.reshape(new_positions.T, (n*m))
    new_momentums = np.reshape(new_momentums.T, (n*m))
    return np.hstack([new_positions,new_momentums])

In [38]:
def f_direct(vector, delta):
    positions, momentums = np.split(vector,2)
    positions = np.reshape(positions,(3,len(positions)/3)).T
    momentums = np.reshape(momentums,(3,len(momentums)/3)).T
    new_positions = direct_position(positions, momentums,delta)
    new_momentums = direct_momentum(positions, momentums,delta)
    n,m = new_positions.shape
    new_positions = np.reshape(new_positions.T, (n*m))
    new_momentums = np.reshape(new_momentums.T, (n*m))
    return np.hstack([new_positions,new_momentums])

In [ ]:
X = np.loadtxt('data/sphere_x.txt')
Y = np.loadtxt('data/sphere_y.txt')
Z = np.loadtxt('data/sphere_z.txt')

X1 = np.hstack((X,Y,Z))

A = np.loadtxt('data/alpha0_x.txt')
B = np.loadtxt('data/alpha0_y.txt')
C = np.loadtxt('data/alpha0_z.txt')

alpha1 = np.hstack((A,B,C))

vector = np.hstack([X1,alpha1])
vector1 = f(vector, delta)

positions, momentums = np.split(vector1,2)
positions = np.reshape(positions,(3,len(positions)/3)).T
momentums = np.reshape(momentums,(3,len(momentums)/3)).T
print np.sum(np.abs(postition2-positions))
print np.sum(np.abs(momentum2-momentums))

In [39]:
def shoot(alpha, x_a, x_b, sigma,steps):
    #Making lambda function to integrate
    g = lambda y,t: f_direct(y,sigma)
    
    x_i = x_a
    a_i = alpha
    
    #Linealizing vectors
    n,m = x_i.shape
    x_i = np.reshape(x_i.T, (n*m))
    #a_i = np.reshape(a_i.T, (n*m))
    
    vector = np.hstack([x_i,a_i])
    #Integrate over time
    t = np.linspace(0,1,steps)
    matrix = odeint(g,vector,t)
    
    vector = matrix[-1]
    x_b = np.reshape(x_b.T, (n*m))
    x_i, momentums = np.split(vector,2)
    print np.linalg.norm(x_i - x_b)/np.linalg.norm(x_b)
    return x_i - x_b

In [40]:
def shootingMethod(x_a, x_b, alpha0, steps, sigma):
    alpha = root(shoot, alpha0, (x_a,x_b,sigma,steps))
    return alpha

In [ ]:
sigma = 6.5 * (2 ** 0.5)
cut = 10
X = np.loadtxt('data/sphere_x.txt')[0:cut]
Y = np.loadtxt('data/sphere_y.txt')[0:cut]
Z = np.loadtxt('data/sphere_z.txt')[0:cut]

X0 = np.dstack((X,Y,Z))[0]
alpha0 = np.random.random(X0.shape[0]* X0.shape[1])
X = np.loadtxt('data/vent_x.txt')[0:cut]
Y = np.loadtxt('data/vent_y.txt')[0:cut]
Z = np.loadtxt('data/vent_z.txt')[0:cut]

X1 = np.dstack((X,Y,Z))[0]

%timeit alpha = shootingMethod(X0, X1, alpha0, 3, sigma)

0.167398067109
0.167398067109
0.167398067109
0.167398067118
0.167398067108
0.167398067111
0.167398067109
0.167398067112
0.167398067109
0.167398067109
0.167398067111
0.167398067116
0.167398067109
0.167398067109