In [2]:
import numpy as np
import sympy as sp
from scipy.optimize import fsolve
t, y = sp.symbols("t y", real=True)

In [69]:
#def f(y):
#    y1, y2 = y
#    return np.array([-y1**2, y2**(1./2.)])
#def df(y):
#    y1, y2 = y
#    return np.array([[-2.*y1, 0], [0, 0.5*y2**(-0.5)]])
def f(y):
    y1, y2 = y
    return np.array([-y1 + y2, 3*y1 - 7*y2])

def df(y):
    y1, y2 = y
    return np.array([[-1., 1.], [3., -7.]])

def sol(y):
    return np.array([1./(1. + y), ((1./4.)*(y - 2)**2)])
## y = y_i+1
def F(y, y_i, h, f):
    return y - y_i - h*f(y)

def dF(y, h, df):
    return 1. - h*df(y)

def newton(y_0, h, f, df, maxiter = 10000, tol = 1e-10):
    y = y_0.copy()
    for j in range(maxiter):
        ##w = F(t, y, y_0, h)/dF(t, y, h)
        w = np.linalg.solve(dF(y, h, df), -1*F(y, y_0, h, f))
        y += w
        if np.linalg.norm(F(y, y_0, h, f)) < tol:
            break
    return y

def solver(f, df, h, y_0, t_0, t_f):
    n = int((t_f-t_0)/h)
    y = np.zeros((n+1,len(y_0)))
    trange = np.linspace(t_0, t_f, n+1)
    y[0] = y_0
    for i in range(1,n+1):
        #y[i] = fsolve(F, x0 = y[i-1], args = (y[i-1], h))
        y[i] = newton(y[i-1], h, f, df)
    return y, trange
    

In [73]:
y, t = solver(f, df, 0.2, np.array([1,1]), 0, 1)
print sol(t).T - y

[[ 0.          0.        ]
 [-0.10869565  0.15782609]
 [-0.1521289   0.15165721]
 [-0.16379117  0.08932605]
 [-0.15938416  0.01431759]
 [-0.14673616 -0.05571838]]


In [74]:
sol(t).T

array([[ 1.        ,  1.        ],
       [ 0.83333333,  0.81      ],
       [ 0.71428571,  0.64      ],
       [ 0.625     ,  0.49      ],
       [ 0.55555556,  0.36      ],
       [ 0.5       ,  0.25      ]])

In [75]:
y

array([[ 1.        ,  1.        ],
       [ 0.94202899,  0.65217391],
       [ 0.86641462,  0.48834279],
       [ 0.78879117,  0.40067395],
       [ 0.71493971,  0.34568241],
       [ 0.64673616,  0.30571838]])

In [50]:
F(np.array([1,1]), np.array([1,1]), 0.2, f)

array([ 0. ,  0.8])

In [49]:
dF(np.array([0,0]), 0.2, df)

array([[ 1.2,  0.8],
       [ 0.4,  2.4]])

In [52]:
w = np.linalg.solve(dF(np.array([0,0]), 0.2, df), -1*F(np.array([1,1]), np.array([1,1]), 0.2, f))
print w

[ 0.25  -0.375]


In [54]:
w = np.linalg.solve(dF(np.array([0,0]), 0.2, df), -1*F(np.array([1+0.25,1-0.375]), np.array([1,1]), 0.2, f))
print w

[-0.4296875   0.17578125]


In [55]:
w = np.linalg.solve(dF(np.array([0,0]), 0.2, df), -1*F(np.array([1+0.25-0.4296875,1-0.375+0.17578125]), np.array([1,1]), 0.2, f))
print w

[ 0.29907227 -0.22888184]
