In [3]:
import numpy as np
import sympy as sp
from scipy.optimize import fsolve

In [60]:
#def f(y):
#    y1, y2 = y
#    return np.array([-y1**2, y2**(1./2.)])
#def df(y):
#    y1, y2 = y
#    return np.array([[-2.*y1, 0], [0, 0.5*y2**(-0.5)]])

## Function of the Differential Problem
def f(y):
    y1, y2 = y
    return np.array([-y1 + y2, 3*y1 - 7*y2])

## Jacobian of the problem
def df(y):
    y1, y2 = y
    return np.array([[-1., 1.], [3., -7.]])

## Real (analytic) solution of differential problem
def sol(y):
    return np.array([1./(1. + y), ((1./4.)*(y - 2)**2)])

## F for solve F(y) = 0 with Newton method. 
## y = y_i+1
def F(y, y_0, h, f):
    return y - y_0 - h*f(y)

## Jacobian of F
def dF(y, h, df):
    return 1. - h*df(y)

## Implicit midpoint Rule
## Here we use y_i+1 = y_1 + h*f((y_i+1 + y_i)/2)
def Fi(y, y_0, h, f):
    return y - y_0 - h*f((y+y_0)*0.5)

## Jacobian of Fi, using chain's rule.
def dFi(y, h, df):
    return 1. - 0.5*h*df(y)

def newton(y_0, h, f, df, maxiter = 10000, tol = 1e-10):
    #Initial Guess
    y = y_0.copy()
    for j in range(maxiter):
        #Step calculation
        w = np.linalg.solve(dF(y, h, df), -1*F(y, y_0, h, f))
        y += w
        ## Found an acceptable solution
        if np.linalg.norm(F(y, y_0, h, f)) < tol:
            break
    return y

def solver(f, df, h, y_0, t_0, t_f):
    n = int((t_f-t_0)/h)
    y = np.zeros((n+1,len(y_0)))
    trange = np.linspace(t_0, t_f, n+1)
    y[0] = y_0.copy()
    for i in range(1,n+1):
        y[i] = newton(y[i-1], h, f, df)
    return y, trange
    

In [62]:
y, t = solver(f, df, 0.2, np.array([1,1]), 0, 1)
print abs(sol(t).T - y)

[[ 0.          0.        ]
 [ 0.10869565  0.15782609]
 [ 0.1521289   0.15165721]
 [ 0.16379117  0.08932605]
 [ 0.15938416  0.01431759]
 [ 0.14673616  0.05571838]]


In [63]:
sol(t).T

array([[ 1.        ,  1.        ],
       [ 0.83333333,  0.81      ],
       [ 0.71428571,  0.64      ],
       [ 0.625     ,  0.49      ],
       [ 0.55555556,  0.36      ],
       [ 0.5       ,  0.25      ]])

In [64]:
y

array([[ 1.        ,  1.        ],
       [ 0.94202899,  0.65217391],
       [ 0.86641462,  0.48834279],
       [ 0.78879117,  0.40067395],
       [ 0.71493971,  0.34568241],
       [ 0.64673616,  0.30571838]])

In [39]:
A = np.array([[-1,1], [3,-7]])
print np.linalg.eig(A)

(array([-0.53589838, -7.46410162]), array([[ 0.90707274, -0.15288195],
       [ 0.42097392,  0.98824446]]))


In [1]:
0.01*np.linalg.eig(A)[0][0]

NameError: name 'np' is not defined